eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8774
spring:
  application:
    name: microservice-client-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: microservice-client-ribbon
    api-b:
      path: /api-b/**
      serviceId: microservice-client-feign